// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: GaggiMate

#include "../../../main.h"
#include "../../../plugins/BLEScalePlugin.h"
#include "ui.h"
#include <Arduino.h>

// Flag to track if volumetric hold was triggered
static bool volumetricHoldTriggered = false;
static int manualTempPixels = 0;
static int manualPressurePixels = 0;
static constexpr int MANUAL_TEMP_PIXELS_PER_STEP = 18;
static constexpr int MANUAL_PRESSURE_PIXELS_PER_STEP = 8;
static constexpr float MANUAL_PRESSURE_STEP = 0.2f;
static Profile manualProfileBackup{};
static bool manualProfileBackupValid = false;
static uint32_t manualShotStartMs = 0;
static uint32_t manualShotDurationMs = 0;
static bool manualShotInProgress = false;
static std::vector<std::pair<uint32_t, float>> manualPressureTimeline;
static constexpr size_t MANUAL_PROFILE_MAX_STEPS = 12;

static void applyManualTempTarget(float temperature);
static float getManualPressureTarget();
static void setManualPressureTarget(float targetPressure);

static std::vector<std::pair<uint32_t, float>> compressManualPressureTimeline(
    const std::vector<std::pair<uint32_t, float>> &timeline) {
    if (timeline.size() <= 2) {
        return timeline;
    }

    // First pass: collapse transient ramp points that lie on the same directional move.
    std::vector<std::pair<uint32_t, float>> reduced;
    reduced.reserve(timeline.size());
    reduced.push_back(timeline.front());

    for (size_t i = 1; i + 1 < timeline.size(); ++i) {
        const auto &prev = reduced.back();
        const auto &curr = timeline[i];
        const auto &next = timeline[i + 1];

        const float d1 = curr.second - prev.second;
        const float d2 = next.second - curr.second;
        const bool sameDirection = (d1 == 0.0f || d2 == 0.0f || (d1 > 0.0f && d2 > 0.0f) || (d1 < 0.0f && d2 < 0.0f));

        // Treat quick intermediate updates as part of the same sweep gesture.
        const bool shortTransient = (curr.first - prev.first) < 1200 && fabsf(curr.second - prev.second) < 0.8f;

        // Drop near-collinear points between previous kept point and next point.
        bool nearLinear = false;
        if (next.first > prev.first) {
            const float t = static_cast<float>(curr.first - prev.first) / static_cast<float>(next.first - prev.first);
            const float interpolated = prev.second + (next.second - prev.second) * t;
            nearLinear = fabsf(curr.second - interpolated) < 0.25f;
        }

        if (sameDirection && (shortTransient || nearLinear)) {
            continue;
        }

        reduced.push_back(curr);
    }

    reduced.push_back(timeline.back());

    if (reduced.size() <= MANUAL_PROFILE_MAX_STEPS) {
        return reduced;
    }

    // Second pass: hard-cap to MANUAL_PROFILE_MAX_STEPS while preserving start/end and overall shape.
    std::vector<std::pair<uint32_t, float>> capped;
    capped.reserve(MANUAL_PROFILE_MAX_STEPS);
    capped.push_back(reduced.front());

    const size_t lastIndex = reduced.size() - 1;
    size_t lastAddedIndex = 0;
    for (size_t k = 1; k + 1 < MANUAL_PROFILE_MAX_STEPS; ++k) {
        size_t idx = (k * lastIndex) / (MANUAL_PROFILE_MAX_STEPS - 1);
        if (idx <= lastAddedIndex) {
            idx = std::min(lastIndex - 1, idx + 1);
        }
        capped.push_back(reduced[idx]);
        lastAddedIndex = idx;
    }

    if (capped.back() != reduced.back()) {
        capped.push_back(reduced.back());
    }

    return capped;
}

static void recordManualPressurePoint(float pressure) {
    if (!manualShotInProgress) {
        return;
    }

    const uint32_t nowMs = millis();
    const uint32_t elapsedMs = nowMs >= manualShotStartMs ? (nowMs - manualShotStartMs) : 0;

    if (!manualPressureTimeline.empty()) {
        const float lastPressure = manualPressureTimeline.back().second;
        if (fabsf(lastPressure - pressure) < 0.01f) {
            return;
        }
    }

    manualPressureTimeline.emplace_back(elapsedMs, pressure);
}

static void applyManualTimelineToProfile(Profile &profile) {
    if (manualPressureTimeline.empty()) {
        return;
    }

    const auto timeline = compressManualPressureTimeline(manualPressureTimeline);
    if (timeline.empty()) {
        return;
    }

    const float scaling = controller.getSettings().getPressureScaling();
    float shotDurationSec = static_cast<float>(manualShotDurationMs) / 1000.0f;
    if (shotDurationSec < 0.5f) {
        shotDurationSec = static_cast<float>((millis() >= manualShotStartMs) ? (millis() - manualShotStartMs) : 0) / 1000.0f;
    }
    shotDurationSec = std::max(0.5f, shotDurationSec);

    std::vector<Phase> phases;
    phases.reserve(timeline.size());

    for (size_t i = 0; i < timeline.size(); ++i) {
        const float startSec = static_cast<float>(timeline[i].first) / 1000.0f;
        const float endSec = (i + 1 < timeline.size())
                                 ? static_cast<float>(timeline[i + 1].first) / 1000.0f
                                 : shotDurationSec;
        const float duration = std::max(0.5f, endSec - startSec);

        Phase phase{};
        phase.name = (i == 0) ? "Manual Brew" : ("Manual Brew " + String(static_cast<int>(i + 1)));
        phase.phase = PhaseType::PHASE_TYPE_BREW;
        phase.valve = 1;
        phase.duration = duration;
        phase.pumpIsSimple = false;
        phase.pumpAdvanced.target = PumpTarget::PUMP_TARGET_PRESSURE;
        phase.pumpAdvanced.pressure = constrain(timeline[i].second, 0.0f, scaling);
        phase.pumpAdvanced.flow = 0.0f;
        phase.temperature = profile.temperature;
        phase.transition = Transition{.type = TransitionType::INSTANT, .duration = 0.0f, .adaptive = false};
        phases.push_back(phase);
    }

    if (!phases.empty()) {
        profile.phases = std::move(phases);
    }
}

static void applyManualTempTarget(float temperature) {
    controller.setTargetTemp(temperature);
}

static void backupManualProfile() {
    manualProfileBackup = controller.getProfileManager()->getSelectedProfile();
    manualProfileBackupValid = true;
}

static void restoreManualProfile() {
    if (!manualProfileBackupValid) {
        return;
    }

    controller.getProfileManager()->getSelectedProfile() = manualProfileBackup;
    manualProfileBackupValid = false;
    manualTempPixels = 0;
    manualPressurePixels = 0;
    controller.getUI()->markDirty();
}

static float getManualPressureTarget() {
    const auto &profile = controller.getProfileManager()->getSelectedProfile();
    for (const auto &phase : profile.phases) {
        if (phase.phase == PhaseType::PHASE_TYPE_BREW && !phase.pumpIsSimple) {
            return phase.pumpAdvanced.pressure;
        }
    }

    const float scaling = controller.getSettings().getPressureScaling();
    const float fallback = controller.getCurrentPressure() > 0.0f ? controller.getCurrentPressure() : 0.0f;
    return constrain(fallback, 0.0f, scaling);
}

static int parseManualProfileNumber(const String &label) {
    if (label == "Manual") {
        return 1;
    }

    if (!label.startsWith("Manual ")) {
        return 0;
    }

    const String numberPart = label.substring(7);
    if (numberPart.isEmpty()) {
        return 0;
    }

    for (size_t i = 0; i < numberPart.length(); ++i) {
        if (numberPart[i] < '0' || numberPart[i] > '9') {
            return 0;
        }
    }

    const int parsed = numberPart.toInt();
    return parsed > 0 ? parsed : 0;
}

// Find next available Manual N number for naming saved profiles.
static int findNextManualProfileNumber() {
    auto *pm = controller.getProfileManager();
    if (!pm) return 1;

    std::vector<int> usedNumbers;
    usedNumbers.reserve(16);
    int maxNumber = 0;
    const auto uuids = pm->listProfiles();

    for (const auto &uuid : uuids) {
        Profile p;
        if (!pm->loadProfile(uuid, p)) continue;

        const int number = parseManualProfileNumber(p.label);
        if (number <= 0) {
            continue;
        }

        usedNumbers.push_back(number);
        if (number > maxNumber) {
            maxNumber = number;
        }
    }

    for (int candidate = 1; candidate <= maxNumber + 1; ++candidate) {
        bool taken = false;
        for (const int used : usedNumbers) {
            if (used == candidate) {
                taken = true;
                break;
            }
        }
        if (!taken) {
            return candidate;
        }
    }

    return maxNumber + 1;
}

static void setManualPressureTarget(float targetPressure) {
    const float scaling = controller.getSettings().getPressureScaling();
    const float clamped = constrain(targetPressure, 0.0f, scaling);
    controller.setManualPressureTarget(clamped);
    recordManualPressurePoint(clamped);

    // Immediate display update for snappy pressure control response
    if (ui_ManualBrewScreen_pressureTarget) {
        const float displayPressure = std::round(clamped * 10.0f) / 10.0f;
        char pressureTargetText[8];
        std::snprintf(pressureTargetText, sizeof(pressureTargetText), "%.1f", displayPressure);
        lv_label_set_text(ui_ManualBrewScreen_pressureTarget, pressureTargetText);
    }
    
    if (uic_ManualBrewScreen_dials_pressureTarget) {
        const double pct = 1.0 - static_cast<double>(clamped) / static_cast<double>(std::max(1, static_cast<int>(scaling)));
        const double start = -62.0;
        const double range = 124.0;
        double angle = start + range - range * pct;
        lv_img_set_angle(uic_ManualBrewScreen_dials_pressureTarget, angle * -10);
        int x = static_cast<int>(std::cos(angle * M_PI / 180.0f) * 235.0);
        int y = static_cast<int>(std::sin(angle * M_PI / 180.0f) * -235.0);
        lv_obj_set_pos(uic_ManualBrewScreen_dials_pressureTarget, x, y);
    }

    controller.getUI()->markProfileDirty();
    controller.getUI()->markDirty();
}

void onBrewCancel(lv_event_t *e) {
    controller.deactivate();
    controller.clear();
}

void onBrewStart(lv_event_t *e) { controller.activate(); }

void onBrewTempLower(lv_event_t *e) {
    controller.getUI()->markProfileDirty();
    controller.lowerTemp();
}

void onBrewTempRaise(lv_event_t *e) {
    controller.getUI()->markProfileDirty();
    controller.raiseTemp();
}

void onBrewTimeLower(lv_event_t *e) {
    controller.getUI()->markProfileDirty();
    controller.lowerBrewTarget();
}

void onBrewTimeRaise(lv_event_t *e) {
    controller.getUI()->markProfileDirty();
    controller.raiseBrewTarget();
}

void onSteamTempLower(lv_event_t *e) { controller.lowerTemp(); }

void onSteamTempRaise(lv_event_t *e) { controller.raiseTemp(); }

void onBrewScreen(lv_event_t *e) {
    controller.getUI()->changeScreen(&ui_BrewScreen, &ui_BrewScreen_screen_init);
    controller.deactivate();
    controller.setMode(MODE_BREW);
}

void onWaterScreen(lv_event_t *e) {
    controller.getUI()->changeScreen(&ui_SimpleProcessScreen, &ui_SimpleProcessScreen_screen_init);
    controller.setMode(MODE_WATER);
    controller.deactivate();
}

void onSteamScreen(lv_event_t *e) {
    controller.getUI()->changeScreen(&ui_SimpleProcessScreen, &ui_SimpleProcessScreen_screen_init);
    controller.setMode(MODE_STEAM);
    controller.deactivate();
}

void onWakeup(lv_event_t *e) {
    if (controller.isUpdating() || controller.isErrorState() || controller.isAutotuning() ||
        !controller.getClientController()->isConnected()) {
        return;
    }
    controller.getUI()->changeScreen(&ui_BrewScreen, &ui_BrewScreen_screen_init);
    controller.deactivate();
    controller.setMode(MODE_BREW);
}

void onLoadStarted(lv_event_t *e) {}

void onStandby(lv_event_t *e) { controller.activateStandby(); }

void onGrindToggle(lv_event_t *e) { controller.isGrindActive() ? controller.deactivateGrind() : controller.activateGrind(); }

void onGrindTimeLower(lv_event_t *e) { controller.lowerGrindTarget(); }

void onGrindTimeRaise(lv_event_t *e) { controller.raiseGrindTarget(); }

void onMenuClick(lv_event_t *e) {
    if (controller.getMode() == MODE_MANUAL) {
        restoreManualProfile();
    }
    controller.deactivate();
    controller.setMode(MODE_BREW);
    controller.getUI()->changeScreen(&ui_MenuScreen, &ui_MenuScreen_screen_init);
}

void onManualBrewScreenLoad(lv_event_t *e) {
    lv_obj_set_ext_click_area(ui_ManualBrewScreen_startButton, 25);
    lv_obj_set_ext_click_area(ui_ManualBrewScreen_backButton, 70);
    if (uic_ManualBrewScreen_dials_tempText) {
        // Remove visible tile contrast around temp text on the true-black manual screen.
        lv_obj_set_style_bg_color(uic_ManualBrewScreen_dials_tempText, lv_color_hex(0x000000),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_opa(uic_ManualBrewScreen_dials_tempText, LV_OPA_COVER, LV_PART_MAIN | LV_STATE_DEFAULT);
    }
    if (uic_ManualBrewScreen_dials_tempGauge) {
        lv_obj_set_ext_click_area(uic_ManualBrewScreen_dials_tempGauge, 45);
    }
    if (uic_ManualBrewScreen_dials_pressureGauge) {
        lv_obj_set_ext_click_area(uic_ManualBrewScreen_dials_pressureGauge, 45);
    }
}

void onManualBrewAdjust(lv_event_t *e) {
    lv_obj_t *target = lv_event_get_target(e);
    if (target == ui_ManualBrewScreen_pressureZone) {
        onManualBrewAdjustPressure(e);
        return;
    }
    onManualBrewAdjustTemp(e);
}

void onManualBrewAdjustTemp(lv_event_t *e) {
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_RELEASED || event_code == LV_EVENT_PRESS_LOST) {
        manualTempPixels = 0;
        return;
    }

    if (event_code == LV_EVENT_PRESSED) {
        manualTempPixels = 0;
        return;
    }

    if (event_code != LV_EVENT_PRESSING) {
        return;
    }

    lv_indev_t *indev = lv_indev_get_act();
    if (indev == nullptr) {
        return;
    }

    lv_point_t vector;
    lv_indev_get_vect(indev, &vector);
    manualTempPixels += -vector.y;

    while (abs(manualTempPixels) >= MANUAL_TEMP_PIXELS_PER_STEP) {
        const float step = manualTempPixels > 0 ? 1.0f : -1.0f;
        const float target =
            constrain(controller.getTargetTemp() + step, static_cast<float>(MIN_TEMP), static_cast<float>(MAX_TEMP));
        applyManualTempTarget(target);
        manualTempPixels += manualTempPixels > 0 ? -MANUAL_TEMP_PIXELS_PER_STEP : MANUAL_TEMP_PIXELS_PER_STEP;
    }

    controller.getUI()->markDirty();
}

void onManualBrewAdjustPressure(lv_event_t *e) {
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_RELEASED || event_code == LV_EVENT_PRESS_LOST) {
        manualPressurePixels = 0;
        return;
    }

    if (event_code == LV_EVENT_PRESSED) {
        manualPressurePixels = 0;
        return;
    }

    if (event_code != LV_EVENT_PRESSING) {
        return;
    }

    lv_indev_t *indev = lv_indev_get_act();
    if (indev == nullptr) {
        return;
    }

    lv_point_t vector;
    lv_indev_get_vect(indev, &vector);
    manualPressurePixels += -vector.y;

    // Calculate predicted pressure based on current accumulated pixels (immediate visual feedback)
    const float scaling = controller.getSettings().getPressureScaling();
    const float currentPressure = getManualPressureTarget();
    const int predictedSteps = manualPressurePixels / MANUAL_PRESSURE_PIXELS_PER_STEP;
    const float predictedPressure = constrain(currentPressure + (predictedSteps * MANUAL_PRESSURE_STEP), 0.0f, scaling);

    // Show predicted pressure immediately on display while swiping
    if (ui_ManualBrewScreen_pressureTarget) {
        const float displayPressure = std::round(predictedPressure * 10.0f) / 10.0f;
        char pressureTargetText[8];
        std::snprintf(pressureTargetText, sizeof(pressureTargetText), "%.1f", displayPressure);
        lv_label_set_text(ui_ManualBrewScreen_pressureTarget, pressureTargetText);
    }

    if (uic_ManualBrewScreen_dials_pressureTarget) {
        const double pct = 1.0 - static_cast<double>(predictedPressure) / static_cast<double>(std::max(1, static_cast<int>(scaling)));
        const double start = -62.0;
        const double range = 124.0;
        double angle = start + range - range * pct;
        lv_img_set_angle(uic_ManualBrewScreen_dials_pressureTarget, angle * -10);
        int x = static_cast<int>(std::cos(angle * M_PI / 180.0f) * 235.0);
        int y = static_cast<int>(std::sin(angle * M_PI / 180.0f) * -235.0);
        lv_obj_set_pos(uic_ManualBrewScreen_dials_pressureTarget, x, y);
    }

    while (abs(manualPressurePixels) >= MANUAL_PRESSURE_PIXELS_PER_STEP) {
        const float step = manualPressurePixels > 0 ? MANUAL_PRESSURE_STEP : -MANUAL_PRESSURE_STEP;
        setManualPressureTarget(getManualPressureTarget() + step);
        manualPressurePixels +=
            manualPressurePixels > 0 ? -MANUAL_PRESSURE_PIXELS_PER_STEP : MANUAL_PRESSURE_PIXELS_PER_STEP;
    }

    controller.getUI()->markDirty();
}

void onGrindScreen(lv_event_t *e) {
    const int secondaryAction = controller.getSettings().getSecondaryAction();
    if (secondaryAction == SECONDARY_ACTION_NONE) {
        return;
    }

    if (secondaryAction == SECONDARY_ACTION_GRIND) {
        controller.getUI()->changeScreen(&ui_GrindScreen, &ui_GrindScreen_screen_init);
        controller.setMode(MODE_GRIND);
        return;
    }

    backupManualProfile();
    controller.getUI()->changeScreen(&ui_ManualBrewScreen, &ui_ManualBrewScreen_screen_init);
    controller.deactivate();
    controller.setMode(MODE_MANUAL);
    controller.setManualPressureTarget(0.0f);
    controller.getUI()->markDirty();
}

void onVolumetricClick(lv_event_t *e) {}

void onPreviousProfile(lv_event_t *e) { controller.getUI()->onPreviousProfile(); }

void onNextProfile(lv_event_t *e) { controller.getUI()->onNextProfile(); }

void onProfileLoad(lv_event_t *e) { controller.getUI()->onProfileSelect(); }

void onProfileAdaptiveToggle(lv_event_t *e) { controller.getUI()->onProfileAdaptiveToggle(); }

void onSelectedProfileAdaptiveToggle(lv_event_t *e) { controller.getUI()->onSelectedProfileAdaptiveToggle(); }

void onProfileSelect(lv_event_t *e) { controller.getUI()->onProfileSwitch(); }

void onFlush(lv_event_t *e) { controller.onFlush(); }

void onSimpleProcessToggle(lv_event_t *e) {
    if (controller.getMode() != MODE_STEAM) {
        controller.isActive() ? controller.deactivate() : controller.activate();
    }
}

void onManualBrewToggle(lv_event_t *e) {
    if (controller.getMode() != MODE_MANUAL) {
        controller.setMode(MODE_MANUAL);
    }

    if (controller.isActive()) {
        controller.deactivate();
        if (manualShotInProgress) {
            manualShotDurationMs = (millis() >= manualShotStartMs) ? (millis() - manualShotStartMs) : 0;
            manualShotInProgress = false;
        }
    } else {
        if (ui_ManualBrewScreen_savePanel) {
            lv_obj_add_flag(ui_ManualBrewScreen_savePanel, LV_OBJ_FLAG_HIDDEN);
        }
        controller.activate();
        manualShotStartMs = millis();
        manualShotDurationMs = 0;
        manualShotInProgress = true;
        manualPressureTimeline.clear();
        recordManualPressurePoint(getManualPressureTarget());
    }

    controller.getUI()->markDirty();
}

void onProfileScreenLoad(lv_event_t *e) {
    lv_obj_set_ext_click_area(ui_ProfileScreen_previousProfileBtn, 30);
    lv_obj_set_ext_click_area(ui_ProfileScreen_nextProfileBtn, 30);
    lv_obj_set_ext_click_area(ui_ProfileScreen_chooseButton, 30);
    lv_obj_set_ext_click_area(ui_ProfileScreen_ImgButton1, 20);
}

void onMenuScreenLoad(lv_event_t *e) {
    const int secondaryAction = controller.getSettings().getSecondaryAction();
    if (ui_MenuScreen_grindIcon) {
        if (secondaryAction == SECONDARY_ACTION_MANUAL_BREW) {
            lv_img_set_src(ui_MenuScreen_grindIcon, &ui_img_manual_pressure_80x80);
            lv_img_set_zoom(ui_MenuScreen_grindIcon, 256);
            lv_obj_set_style_img_recolor(ui_MenuScreen_grindIcon, lv_color_hex(0x2CA4F6), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_img_recolor_opa(ui_MenuScreen_grindIcon, LV_OPA_COVER, LV_PART_MAIN | LV_STATE_DEFAULT);
        } else {
            lv_img_set_src(ui_MenuScreen_grindIcon, &ui_img_363557387);
            lv_img_set_zoom(ui_MenuScreen_grindIcon, 256);
            ui_object_set_themeable_style_property(ui_MenuScreen_grindIcon, LV_PART_MAIN | LV_STATE_DEFAULT,
                                                   LV_STYLE_IMG_RECOLOR, _ui_theme_color_NiceWhite);
            ui_object_set_themeable_style_property(ui_MenuScreen_grindIcon, LV_PART_MAIN | LV_STATE_DEFAULT,
                                                   LV_STYLE_IMG_RECOLOR_OPA, _ui_theme_alpha_NiceWhite);
        }
        lv_obj_center(ui_MenuScreen_grindIcon);
    }

    lv_obj_set_ext_click_area(ui_MenuScreen_btnBrew, 15);
    lv_obj_set_ext_click_area(ui_MenuScreen_btnSteam, 15);
    lv_obj_set_ext_click_area(ui_MenuScreen_waterBtn, 15);
    lv_obj_set_ext_click_area(ui_MenuScreen_grindBtn, 15);
    lv_obj_set_ext_click_area(ui_MenuScreen_standbyButton, 20);
}

void onBrewScreenLoad(lv_event_t *e) {
    lv_obj_set_ext_click_area(ui_BrewScreen_startButton, 25);
    lv_obj_set_ext_click_area(ui_BrewScreen_profileSelectBtn, 25);
    lv_obj_set_ext_click_area(ui_BrewScreen_ImgButton5, 20);
    lv_obj_set_ext_click_area(ui_BrewScreen_upDurationButton, 15);
    lv_obj_set_ext_click_area(ui_BrewScreen_downDurationButton, 15);
    lv_obj_set_ext_click_area(ui_BrewScreen_upTempButton, 15);
    lv_obj_set_ext_click_area(ui_BrewScreen_downTempButton, 15);
    lv_obj_set_ext_click_area(ui_BrewScreen_tempContainer, 20);
    lv_obj_set_ext_click_area(ui_BrewScreen_Label1, 20);
}

void onSimpleProcessScreenLoad(lv_event_t *e) {
    lv_obj_set_ext_click_area(ui_SimpleProcessScreen_downTempButton, 40);
    lv_obj_set_ext_click_area(ui_SimpleProcessScreen_upTempButton, 40);
    lv_obj_set_ext_click_area(ui_SimpleProcessScreen_goButton, 25);
    lv_obj_set_ext_click_area(ui_SimpleProcessScreen_ImgButton6, 20);
    lv_obj_set_ext_click_area(ui_SimpleProcessScreen_targetTemp, 60);
}

void onStatusScreenLoad(lv_event_t *e) {
    lv_obj_set_ext_click_area(ui_StatusScreen_pauseButton, 25);
    lv_obj_set_ext_click_area(ui_StatusScreen_ImgButton8, 20);
}

void onGrindScreenLoad(lv_event_t *e) {
    lv_obj_set_ext_click_area(ui_GrindScreen_upDurationButton, 40);
    lv_obj_set_ext_click_area(ui_GrindScreen_downDurationButton, 40);
    lv_obj_set_ext_click_area(ui_GrindScreen_startButton, 25);
    lv_obj_set_ext_click_area(ui_GrindScreen_ImgButton2, 20);
}

void onProfileSettings(lv_event_t *e) { controller.getUI()->onBrewSettingsButton(); }

void onProfileSave(lv_event_t *e) {
    controller.onProfileSave();
    controller.getUI()->markProfileClean();
    controller.getUI()->changeBrewScreenMode(BrewScreenState::Brew);
}

void onProfileAccept(lv_event_t *e) { controller.getUI()->changeBrewScreenMode(BrewScreenState::Brew); }

void onProfileSaveAsNew(lv_event_t *e) {
    controller.onProfileSaveAsNew();
    controller.getUI()->markProfileClean();
    controller.getUI()->changeBrewScreenMode(BrewScreenState::Brew);
}

void onVolumetricHold(lv_event_t *e) {
    // Set flag to prevent click from firing when button is released
    volumetricHoldTriggered = true;

    controller.getClientController()->tare();
    BLEScales.tare();
}

void onVolumetricDelete(lv_event_t *e) { controller.getUI()->onVolumetricDelete(); }

void onManualBrewSave(lv_event_t *e) {
    if (!ui_ManualBrewScreen_savePanel) {
        return;
    }

    auto *pm = controller.getProfileManager();
    if (!pm) {
        Serial.println("ERROR: ProfileManager unavailable");
        return;
    }

    // Reuse the number shown in the save panel to avoid expensive scans on click.
    int nextNumber = 0;
    if (ui_ManualBrewScreen_saveNameLabel) {
        const char *labelText = lv_label_get_text(ui_ManualBrewScreen_saveNameLabel);
        if (labelText != nullptr) {
            nextNumber = parseManualProfileNumber(String(labelText));
        }
    }
    if (nextNumber <= 0) {
        nextNumber = findNextManualProfileNumber();
    }

    Serial.printf("Saving manual profile: Manual %d\n", nextNumber);
    
    Profile newProfile = pm->getSelectedProfile();
    newProfile.id = ""; // Force new UUID on save
    newProfile.label = "Manual " + String(nextNumber);
    applyManualTimelineToProfile(newProfile);

    const bool saved = pm->saveProfile(newProfile);
    if (saved) {
        auto profileOrder = controller.getSettings().getProfileOrder();
        if (std::find(profileOrder.begin(), profileOrder.end(), newProfile.id) == profileOrder.end()) {
            profileOrder.push_back(newProfile.id);
            controller.getSettings().setProfileOrder(std::move(profileOrder));
        }
        pm->addFavoritedProfile(newProfile.id);
        pm->selectProfile(newProfile.id);
        Serial.printf("Profile saved successfully: %s (%s)\n", newProfile.label.c_str(), newProfile.id.c_str());
        lv_obj_add_flag(ui_ManualBrewScreen_savePanel, LV_OBJ_FLAG_HIDDEN);
        manualPressureTimeline.clear();
        manualShotDurationMs = 0;
    } else {
        Serial.println("ERROR: Manual profile save failed");
    }
}

void onManualBrewDiscard(lv_event_t *e) {
    if (ui_ManualBrewScreen_savePanel)
        lv_obj_add_flag(ui_ManualBrewScreen_savePanel, LV_OBJ_FLAG_HIDDEN);
}